### ISSUE TITLE
Supporting Facebook sign-in ( Bounty added! )

### ISSUE THREAD

**Issue by tarouboy** [tarouboy/react-native-app-auth#1]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/tarouboy/react-native-app-auth/issues/1)

Can anyone make this package work with Facebook sign-in?
I really want to unlink the FB SDK because they have been adding all the auto-collected events that couldn't opt out.

I would like to add $50 as bounty if someone could help.
Please PM for payment after a PR is submitted.

https://github.com/FormidableLabs/react-native-app-auth/issues/656

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars.githubusercontent.com/u/21119498?v=4' alt='tarouboy' width=24 height=24> tarouboy](https://issuehunt.io/u/tarouboy) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/tarouboy/react-native-app-auth/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by MCPE-PC** [comment]
Hi,
Facebook doesn't follow OAuth2 spec, while it seems to do.

You can [mock the Facebook SDK](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) (but it goes way too far).

I'd recommend you to check out [Facebook Login for Devices](https://developers.facebook.com/docs/facebook-login/for-devices).
The feature is explicitly for the no-SDK use cases.

If needed: I can personally help you to implement "Facebook Login for Devices" in React Native, and bounties included.

**Comment by tarouboy** [comment]
> Hi,
> Facebook doesn't follow OAuth2 spec, while it seems to do.
> 
> You can [mock the Facebook SDK](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow) (but it goes way too far).
> 
> I'd recommend you to check out [Facebook Login for Devices](https://developers.facebook.com/docs/facebook-login/for-devices).
> The feature is explicitly for the no-SDK use cases.
> 
> If needed: I can personally help you to implement "Facebook Login for Devices" in React Native, and bounties included.

Thank you. I will take a look at FB Login for Devices first and let you know if I can handle it.
